
// QUESTION

export const ADD_QUESTION = "ADD_QUESTION";
export const GET_QUESTION_BY_ID = "GET_QUESTION_BY_ID";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";

//USER

export const ADD_USER = "ADD_USER";


